name: Mini CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:

    name: Build Application

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.ver }}

    
    steps:
    
      - name: checkout code
      
        uses: actions/checkout@v4
        
      - name: Generate version

        id: version
        run: echo "ver=v1.0.0" >> $GITHUB_OUTPUT

      - name: Build Application
      
        run: |
          echo "Building Application"
          echo "Version 1.0.0" > build.txt

      - name: Display GitHub Context
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: upload Build Artifact
        uses: actions/upload-artifact@v4

        with:
          name: build-file
          path: build.txt

  test:
    name: Run Tests

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4

        with:
          name: build-file

      - name: Display Artifact Content
        run: cat build.txt

      - name: run python application
        run: python app.py

  lint:
    name: Run Lint checks

    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run lint
        run: echo " lint check passed"

  deploy:

    name: deploy application

    needs: 
      - build
      - test
      - lint

    if: success()

    runs-on: ubuntu-latest

    steps:
      - name: show version
        run: echo "deploying version ${{ needs.build.outputs.version }}"

      - name: deploy application
        run: echo " deployment successful"
